apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobkuw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobkuw
  template:
    metadata:
      labels:
        app: cobkuw
    spec:
      containers:
      - image: okteto.dev/cobkuw:latest
        name: cobkuw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.vecteezy.com"
        - name: Vless_UUID
          value: "deaf485d-1ef0-49f6-a41a-533cc82b5fbb"
        - name: Vless_Path
          value: "/deaf485d-1ef0-49f6-a41a-533cc82b5fbb"
        - name: Vmess_UUID
          value: "05139c18-af58-441e-82db-a73209239f70"
        - name: Vmess_Path
          value: "/05139c18-af58-441e-82db-a73209239f70"
        - name: Share_Path
          value: "/Share204"
