apiVersion: v1
kind: reuigq
metadata:
  name: reuigq
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "reuigq"
    port: 8080
  selector:
    app: reuigq
