apiVersion: v1
kind: Service
metadata:
  name: deppur
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "deppur"
    port: 8080
  selector:
    app: deppur
